/*
 * dump_reference_int8.c -- fixes a NATIVE reference for the int8 GEMM kernel.
 *
 * T73's acceptance criterion is that the deterministic int8 path (`i32x4.dot_i16x8_s`
 * in Wasm, SSE2/AVX2/scalar natively) stays bit-for-bit -- not within a
 * tolerance -- across native and WebAssembly, because integer addition is
 * associative and the whole point of the int8 path is that this guarantee is
 * unconditional. `wasm-parity` already proves the float32 network at 1e-6; this
 * is the same idea applied to the int8 kernel alone, at EXACT equality.
 *
 * The comparison must be kernel-to-kernel, not layer-to-layer of the whole
 * network: no exported model is quantised yet (a separate, larger piece of
 * work -- see docs/mesures/2026-08-31-T73-qat-echelle-diagnostic.md). So the
 * test vectors here are SYNTHETIC, generated by the same deterministic
 * xorshift PRNG and the same five layer shapes `bench_gemm_int8.c` already
 * uses -- the shapes the embedded network actually has, at the batch width
 * the engine forwards (32).
 *
 * Both kernels are exercised on every shape (not just the one each is used
 * for in real inference) -- broader coverage costs nothing here since there is
 * no rollout, just five small GEMMs.
 *
 * File layout, flat and binary so a JS reader has nothing to parse:
 *
 *     uint32    magic 'GNI8'
 *     int32     number of layers (5)
 *     int32     batch (32)
 *     int32     shift (7)
 *     per layer:
 *       int32   rows, cols
 *       int8[]  weights, rows x cols
 *       int32[] bias, rows
 *       uint8[] input, cols x batch (feature-major)
 *       uint8[] relu_out, rows x batch  -- from gn_gemm_int8_relu
 *       int32[] raw_out,  rows x batch  -- from gn_gemm_int8_raw
 *
 *     tools/dump_reference_int8  (no arguments; writes build/reference_int8.bin)
 *
 * SPDX-License-Identifier: MIT
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include "gn_gemm_int8.h"

#define BATCH 32
#define SHIFT 7
#define MAGIC 0x38494e47u /* 'GNI8' little-endian */

static const struct { int rows, cols; } LAYERS[] = {
    {512, 196}, {512, 512}, {256, 512}, {128, 256}, {5, 128},
};
#define NUM_LAYERS ((int)(sizeof(LAYERS) / sizeof(LAYERS[0])))

/* Same generator and stream as bench_gemm_int8.c, so a reader diffing the two
 * files by eye recognises the same numbers -- not load-bearing, just a
 * courtesy. Not shared via a header: fourteen lines, not worth a dependency
 * between a benchmark and a correctness dump. */
static unsigned long rng_state = 88172645463325252UL;
static unsigned long xorshift(void)
{
    rng_state ^= rng_state << 13;
    rng_state ^= rng_state >> 7;
    rng_state ^= rng_state << 17;
    return rng_state;
}

static void write_i32(FILE *f, int32_t v) { fwrite(&v, sizeof v, 1, f); }
static void write_u32(FILE *f, uint32_t v) { fwrite(&v, sizeof v, 1, f); }

int main(void)
{
    FILE *f = fopen("build/reference_int8.bin", "wb");
    if (!f) {
        perror("build/reference_int8.bin");
        return 1;
    }

    write_u32(f, MAGIC);
    write_i32(f, NUM_LAYERS);
    write_i32(f, BATCH);
    write_i32(f, SHIFT);

    for (int L = 0; L < NUM_LAYERS; L++) {
        const int rows = LAYERS[L].rows, cols = LAYERS[L].cols;
        int8_t *weights = malloc((size_t)rows * cols);
        int32_t *bias = malloc((size_t)rows * sizeof(int32_t));
        uint8_t *input = malloc((size_t)cols * BATCH);
        uint8_t *relu_out = malloc((size_t)rows * BATCH);
        int32_t *raw_out = malloc((size_t)rows * BATCH * sizeof(int32_t));
        if (!weights || !bias || !input || !relu_out || !raw_out) {
            fprintf(stderr, "allocation refusée\n");
            return 1;
        }

        for (size_t i = 0; i < (size_t)rows * cols; i++) {
            weights[i] = (int8_t)(xorshift() % 255 - 127);
        }
        for (int i = 0; i < rows; i++) {
            bias[i] = (int32_t)(xorshift() % 20001) - 10000;
        }
        for (size_t i = 0; i < (size_t)cols * BATCH; i++) {
            input[i] = (uint8_t)(xorshift() % 128);
        }

        if (gn_gemm_int8_relu(weights, rows, cols, bias, input, BATCH,
                              SHIFT, relu_out) != 0) {
            fprintf(stderr, "couche %d : gn_gemm_int8_relu refusée\n", L);
            return 1;
        }
        if (gn_gemm_int8_raw(weights, rows, cols, bias, input, BATCH,
                             raw_out) != 0) {
            fprintf(stderr, "couche %d : gn_gemm_int8_raw refusée\n", L);
            return 1;
        }

        write_i32(f, rows);
        write_i32(f, cols);
        fwrite(weights, 1, (size_t)rows * cols, f);
        fwrite(bias, sizeof(int32_t), rows, f);
        fwrite(input, 1, (size_t)cols * BATCH, f);
        fwrite(relu_out, 1, (size_t)rows * BATCH, f);
        fwrite(raw_out, sizeof(int32_t), (size_t)rows * BATCH, f);

        free(weights);
        free(bias);
        free(input);
        free(relu_out);
        free(raw_out);
    }

    fclose(f);
    printf("repère int8 : %d couches, lot %d, décalage %d -> build/reference_int8.bin  "
           "(noyau natif : %s)\n",
           NUM_LAYERS, BATCH, SHIFT, gn_gemm_int8_path());
    return 0;
}
