#!/usr/bin/env python3
"""Génère `src/gn_met_table.h` et son repère de contrôle.

La table Kazaross-XG2 est l'**œuvre de Neil Kazaross**. Cet outil recopie ses
nombres — il n'en invente aucun.

## Deux sources, et pourquoi la première est préférée

1. **`Kazaross-XG2.xml`**, livré avec GNU Backgammon. C'est le **rendu faisant
   autorité** : c'est ce fichier que GNU Backgammon charge par défaut, et donc
   la table contre laquelle toute comparaison future se fera.
2. **blunderDB** (MIT, Copyright (c) 2024 Facteur Pat), `pkg/blunderdb/engine/met.go`
   — la transcription que `BRIEF.md` §3.3 cite comme précédent MIT pour
   embarquer cette table.

Les deux ont été confrontées : **les 625 entrées pré-Crawford coïncident
exactement**. Mais la transcription de blunderDB s'arrête à **24** entrées
post-Crawford là où le XML en porte **25** — la dernière valant 0,001230. La
troncature est sans conséquence pratique, et c'est précisément pour cela qu'elle
serait passée inaperçue.

Le XML est donc préféré, blunderDB restant le second témoin.

**Sur la licence.** Lire ce fichier de données n'est pas dériver du code de GNU
Backgammon. `BRIEF.md` §3.3 est explicite : la table est l'œuvre de Kazaross,
GNU Backgammon n'en est que le véhicule de distribution, et l'attribution va à
son auteur.

Deux fichiers en sortent, et leur séparation est délibérée :

- `src/gn_met_table.h` — la table, compilée dans la bibliothèque ;
- `tests/data/met_reference.json` — **les mêmes valeurs**, conservées à part
  comme repère. Un test qui comparerait la table à elle-même ne prouverait rien ;
  le repère permet au moins de vérifier qu'une régénération future n'a pas
  silencieusement décalé un indice.

L'antisymétrie est contrôlée **avant** l'écriture. Une table qui ne la
respecterait pas décrirait deux jeux différents selon le côté d'où on la lit, et
il vaut mieux s'en apercevoir ici que six mois plus tard sur une décision de
videau.

    python tools/extract_met.py [--source <chemin vers met.go>]
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BLUNDERDB = "https://github.com/kevung/blunderDB.git"
MET_PATH = "pkg/blunderdb/engine/met.go"

# Les emplacements usuels du XML livré par GNU Backgammon.
XML_CANDIDATES = (
    "/usr/local/share/gnubg/met/Kazaross-XG2.xml",
    "/usr/share/gnubg/met/Kazaross-XG2.xml",
)

HEADER = '''/*
 * gn_met_table.h -- the Kazaross-XG2 match equity table, as data.
 *
 * GENERATED FILE. Regenerate with `tools/extract_met.py`; do not edit by hand.
 *
 * ATTRIBUTION. This table is the work of **Neil Kazaross**. It was generated by
 * XG rollouts to 9 points, GNU Backgammon Supremo full rollouts to 15 points,
 * and extended to 25 points by projecting take points. GNU Backgammon is its
 * distribution vehicle, not its author -- see `BRIEF.md` section 3.3 and
 * `THIRD-PARTY.md`.
 *
 * The numbers are read from `Kazaross-XG2.xml`, the rendering GNU Backgammon
 * ships and loads by default -- the authoritative one, and therefore the table
 * any future comparison will be made against. Reading a data file is not
 * deriving from GNU Backgammon's code; the table is Kazaross's work, and the
 * attribution goes to him.
 *
 * They were cross-checked against `blunderDB` (MIT, Copyright (c) 2024 Facteur
 * Pat), the MIT precedent `BRIEF.md` cites: the 625 pre-Crawford entries agree
 * exactly. blunderDB's transcription stops at 24 post-Crawford entries where
 * the XML carries 25, which is why the XML is preferred.
 *
 * PRE-CRAWFORD. `GN_MET_PRE[i][j]` is the match winning chance of the player
 * who needs `i + 1` points, against an opponent who needs `j + 1`.
 *
 * POST-CRAWFORD. `GN_MET_POST[n]` is the TRAILER's match winning chance when
 * the trailer needs `n + 1` points and the leader needs exactly 1.
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef GN_MET_TABLE_H
#define GN_MET_TABLE_H

#define GN_MET_SIZE 25
'''


def go_array(source: str, name: str) -> str:
    """Le littéral de tableau Go nommé `name`, accolades équilibrées."""
    body = source[source.index(f"var {name} = "):]
    body = body[body.index("{"):]
    depth = 0
    for index, char in enumerate(body):
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return body[: index + 1]
    raise ValueError(f"accolades non équilibrées pour {name}")


def numbers(text: str) -> list[float]:
    return [float(x) for x in re.sub(r"[{}]", "", text).replace("\n", " ").split(",")
            if x.strip()]


def from_gnubg_xml(path: Path):
    """Lit le XML faisant autorité. Rend `(pré 25x25, post 25)`."""
    import xml.etree.ElementTree as ET

    root = ET.parse(path).getroot()

    def table(suffix):
        for element in root.iter():
            if element.tag.endswith(suffix):
                return [[float(cell.text) for cell in row
                         if cell.tag.endswith("me")]
                        for row in element if row.tag.endswith("row")]
        return None

    pre = table("pre-crawford-table")
    post = table("post-crawford-table")
    if pre is None or post is None:
        raise ValueError(f"{path} : tables introuvables")
    return pre, post[0]


def find_gnubg_xml(explicit: Path | None) -> Path | None:
    if explicit is not None:
        return explicit if explicit.is_file() else None
    for candidate in XML_CANDIDATES:
        if Path(candidate).is_file():
            return Path(candidate)
    return None


def fetch_source() -> str:
    """Clone superficiel, le temps de lire un fichier."""
    with tempfile.TemporaryDirectory() as directory:
        subprocess.run(
            ["git", "clone", "-q", "--depth", "1", BLUNDERDB, directory],
            check=True,
        )
        return (Path(directory) / MET_PATH).read_text()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--xml", type=Path, default=None,
                        help="Kazaross-XG2.xml ; sinon cherché aux emplacements usuels")
    parser.add_argument("--source", type=Path, default=None,
                        help="met.go local ; sinon blunderDB est cloné")
    parser.add_argument("--from-blunderdb", action="store_true",
                        help="forcer la transcription plutôt que le XML")
    args = parser.parse_args()

    xml = None if args.from_blunderdb else find_gnubg_xml(args.xml)
    if xml is not None:
        pre, post = from_gnubg_xml(xml)
        origin = f"{xml} (GNU Backgammon, rendu faisant autorité)"
    else:
        source = args.source.read_text() if args.source else fetch_source()
        pre = [numbers(row) for row in
               re.findall(r"\{([^{}]*)\}", go_array(source, "kazarossXG2PreCrawford"))]
        post = numbers(go_array(source, "kazarossXG2PostCrawford"))
        origin = "blunderDB, pkg/blunderdb/engine/met.go"
    print(f"source : {origin}")

    if len(pre) != 25 or any(len(row) != 25 for row in pre):
        print(f"table pré-Crawford malformée : {[len(r) for r in pre]}", file=sys.stderr)
        return 1
    if len(post) < 24:
        print(f"table post-Crawford malformée : {len(post)} entrées", file=sys.stderr)
        return 1

    # Contrôlé AVANT d'écrire : une table non antisymétrique n'a pas à entrer
    # dans le dépôt, et le découvrir sur une décision de videau coûterait cher.
    worst = max(abs(pre[i][j] + pre[j][i] - 1.0) for i in range(25) for j in range(25))
    diagonal = max(abs(pre[i][i] - 0.5) for i in range(25))
    if worst > 1e-9 or diagonal > 1e-9:
        print(f"antisymétrie {worst:.3e}, diagonale {diagonal:.3e} — refusé",
              file=sys.stderr)
        return 1
    print(f"antisymétrie : max|MET[i][j] + MET[j][i] - 1| = {worst:.3e}")
    print(f"diagonale    : max|MET[i][i] - 0,5|           = {diagonal:.3e}")

    lines = [HEADER,
             f"\n#define GN_MET_POST_SIZE {len(post)}\n",
             "static const double GN_MET_PRE[GN_MET_SIZE][GN_MET_SIZE] = {"]
    lines += ["    {" + ", ".join(f"{v:.6f}" for v in row) + "}," for row in pre]
    lines += ["};\n", "static const double GN_MET_POST[GN_MET_POST_SIZE] = {"]
    lines += ["    " + ", ".join(f"{v:.6f}" for v in post[i:i + 6]) + ","
              for i in range(0, len(post), 6)]
    lines += ["};\n", "#endif /* GN_MET_TABLE_H */"]

    header = ROOT / "src" / "gn_met_table.h"
    header.write_text("\n".join(lines) + "\n")
    print(f"écrit : {header.relative_to(ROOT)}")

    reference = ROOT / "tests" / "data" / "met_reference.json"
    reference.parent.mkdir(parents=True, exist_ok=True)
    reference.write_text(json.dumps({
        "source": origin,
        "table": "Kazaross-XG2, œuvre de Neil Kazaross",
        "pre": [{"away_a": i + 1, "away_b": j + 1, "mwc": pre[i][j]}
                for i in range(25) for j in range(25)],
        "post": [{"away": n + 1, "mwc": post[n]} for n in range(len(post))],
    }, indent=1, ensure_ascii=False) + "\n")
    print(f"écrit : {reference.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
