#!/usr/bin/env python3
"""Génère `src/gn_met_table.h` et l'export canonique `data/met_kazaross_xg2.json`.

La table Kazaross-XG2 est l'**œuvre de Neil Kazaross**. Cet outil recopie ses
nombres — il n'en invente aucun.

## Une source, et le témoin qui l'a confirmée

**`Kazaross-XG2.xml`**, livré avec GNU Backgammon, est le **rendu faisant
autorité** : c'est ce fichier que GNU Backgammon charge par défaut, et donc la
table contre laquelle toute comparaison future se fera. C'est la seule source
que cet outil lit.

Une transcription indépendante de la même table l'a confirmée : **les 625
entrées pré-Crawford coïncident exactement**. Mais elle ne portait que **24**
entrées post-Crawford là où le XML en porte **25** — la dernière valant
0,001230. Un témoin plus court que la source ne peut pas en tenir lieu ; c'est
pourquoi il n'y a plus qu'un chemin de lecture ici, et c'est aussi ce qui a
motivé l'export canonique ci-dessous (issue #24).

**Sur la licence.** Lire ce fichier de données n'est pas dériver du code de GNU
Backgammon. `BRIEF.md` §3.3 est explicite : la table est l'œuvre de Kazaross,
GNU Backgammon n'en est que le véhicule de distribution, et l'attribution va à
son auteur.

## Une seule transcription faisant foi, trois fichiers qui en découlent (#24)

`gammonNet` est la source de vérité pour cette table (ADR-0003 : une donnée
partagée entre les cibles se décide et se mesure ici). Un seul appel à
`from_gnubg_xml` produit trois fichiers, tous dérivés des mêmes `pre`/`post` en mémoire — ils ne
peuvent donc pas diverger entre eux au sein de cette régénération :

- `src/gn_met_table.h` — la table, compilée dans la bibliothèque native et le
  module WebAssembly, précision `double`, horizon complet (625 entrées
  pré-Crawford, 25 post-Crawford) ;
- `data/met_kazaross_xg2.json` — **l'export canonique**, à lire au lieu de
  retranscrire la table à la main : les mêmes valeurs, en JSON,
  avec la provenance et l'attribution. C'est aussi le repère de contrôle
  qu'utilise `tests/test_met.py` — un test qui comparerait la table C à
  elle-même ne prouverait rien, celui-ci vérifie qu'une régénération future
  n'a pas silencieusement décalé un indice ;
- `data/met_kazaross_xg2.sha256` — l'empreinte SHA-256 de l'export ci-dessus,
  sur le modèle de `models/release_pin.json` : un appelant qui embarque une
  copie de l'export peut vérifier qu'elle n'a pas divergé sans avoir à la
  reparser champ par champ. La table pèse ~5,2 Ko de doubles bruts (650
  entrées) — assez petite pour être embarquée directement partout, sans
  infrastructure de téléchargement à la `release_pin.json` (celle-ci existe
  pour des poids de plusieurs Mo, pas pour cette table).

L'antisymétrie est contrôlée **avant** l'écriture. Une table qui ne la
respecterait pas décrirait deux jeux différents selon le côté d'où on la lit, et
il vaut mieux s'en apercevoir ici que six mois plus tard sur une décision de
videau.

    python tools/extract_met.py [--xml <chemin vers Kazaross-XG2.xml>]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Les emplacements usuels du XML livré par GNU Backgammon.
XML_CANDIDATES = (
    "/usr/local/share/gnubg/met/Kazaross-XG2.xml",
    "/usr/share/gnubg/met/Kazaross-XG2.xml",
)

HEADER = '''/*
 * gn_met_table.h -- the Kazaross-XG2 match equity table, as data.
 *
 * GENERATED FILE. Regenerate with `tools/extract_met.py`; do not edit by hand.
 *
 * ATTRIBUTION. This table is the work of **Neil Kazaross**. It was generated by
 * XG rollouts to 9 points, GNU Backgammon Supremo full rollouts to 15 points,
 * and extended to 25 points by projecting take points. GNU Backgammon is its
 * distribution vehicle, not its author -- see `BRIEF.md` section 3.3 and
 * `THIRD-PARTY.md`.
 *
 * The numbers are read from `Kazaross-XG2.xml`, the rendering GNU Backgammon
 * ships and loads by default -- the authoritative one, and therefore the table
 * any future comparison will be made against. Reading a data file is not
 * deriving from GNU Backgammon's code; the table is Kazaross's work, and the
 * attribution goes to him.
 *
 * They were cross-checked against an independent transcription of the same
 * table: the 625 pre-Crawford entries agree exactly. That transcription is a
 * WITNESS, not a source -- nothing here derives from it -- and it stops at 24
 * post-Crawford entries where the XML carries 25, which is why the XML is
 * preferred.
 *
 * PRE-CRAWFORD. `GN_MET_PRE[i][j]` is the match winning chance of the player
 * who needs `i + 1` points, against an opponent who needs `j + 1`.
 *
 * POST-CRAWFORD. `GN_MET_POST[n]` is the TRAILER's match winning chance when
 * the trailer needs `n + 1` points and the leader needs exactly 1.
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef GN_MET_TABLE_H
#define GN_MET_TABLE_H

#define GN_MET_SIZE 25
'''


def from_gnubg_xml(path: Path):
    """Lit le XML faisant autorité. Rend `(pré 25x25, post 25)`."""
    import xml.etree.ElementTree as ET

    root = ET.parse(path).getroot()

    def table(suffix):
        for element in root.iter():
            if element.tag.endswith(suffix):
                return [[float(cell.text) for cell in row
                         if cell.tag.endswith("me")]
                        for row in element if row.tag.endswith("row")]
        return None

    pre = table("pre-crawford-table")
    post = table("post-crawford-table")
    if pre is None or post is None:
        raise ValueError(f"{path} : tables introuvables")
    return pre, post[0]


def find_gnubg_xml(explicit: Path | None) -> Path | None:
    if explicit is not None:
        return explicit if explicit.is_file() else None
    for candidate in XML_CANDIDATES:
        if Path(candidate).is_file():
            return Path(candidate)
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--xml", type=Path, default=None,
                        help="Kazaross-XG2.xml ; sinon cherché aux emplacements usuels")
    args = parser.parse_args()

    # Une seule source. Le rendu faisant autorité, ou rien : reconstruire la
    # table depuis une transcription tierce, c'est accepter qu'elle soit plus
    # courte que la source sans que rien ne le dise.
    xml = find_gnubg_xml(args.xml)
    if xml is None:
        print("Kazaross-XG2.xml introuvable — donnez-le avec --xml. Cherché : "
              + ", ".join(XML_CANDIDATES), file=sys.stderr)
        return 1
    pre, post = from_gnubg_xml(xml)
    origin = f"{xml} (GNU Backgammon, rendu faisant autorité)"
    print(f"source : {origin}")

    if len(pre) != 25 or any(len(row) != 25 for row in pre):
        print(f"table pré-Crawford malformée : {[len(r) for r in pre]}", file=sys.stderr)
        return 1
    # L'horizon complet (#24) est 25 entrées post-Crawford, pas 24 : un rendu
    # qui n'en porterait que 24 pose la question plutôt que de l'éviter en
    # silence.
    if len(post) < 25:
        print(f"table post-Crawford malformée : {len(post)} entrées, 25 attendues",
              file=sys.stderr)
        return 1

    # Contrôlé AVANT d'écrire : une table non antisymétrique n'a pas à entrer
    # dans le dépôt, et le découvrir sur une décision de videau coûterait cher.
    worst = max(abs(pre[i][j] + pre[j][i] - 1.0) for i in range(25) for j in range(25))
    diagonal = max(abs(pre[i][i] - 0.5) for i in range(25))
    if worst > 1e-9 or diagonal > 1e-9:
        print(f"antisymétrie {worst:.3e}, diagonale {diagonal:.3e} — refusé",
              file=sys.stderr)
        return 1
    print(f"antisymétrie : max|MET[i][j] + MET[j][i] - 1| = {worst:.3e}")
    print(f"diagonale    : max|MET[i][i] - 0,5|           = {diagonal:.3e}")

    lines = [HEADER,
             f"\n#define GN_MET_POST_SIZE {len(post)}\n",
             "static const double GN_MET_PRE[GN_MET_SIZE][GN_MET_SIZE] = {"]
    lines += ["    {" + ", ".join(f"{v:.6f}" for v in row) + "}," for row in pre]
    lines += ["};\n", "static const double GN_MET_POST[GN_MET_POST_SIZE] = {"]
    lines += ["    " + ", ".join(f"{v:.6f}" for v in post[i:i + 6]) + ","
              for i in range(0, len(post), 6)]
    lines += ["};\n", "#endif /* GN_MET_TABLE_H */"]

    header = ROOT / "src" / "gn_met_table.h"
    header.write_text("\n".join(lines) + "\n")
    print(f"écrit : {header.relative_to(ROOT)}")

    # L'export canonique (#24) : une seule écriture de la table, à lire au
    # lieu de la retranscrire. `_comment` porte l'attribution jusque dans le
    # fichier lui-même, pour un appelant qui ne lirait que ce JSON sans jamais
    # ouvrir ce dépôt.
    export = ROOT / "data" / "met_kazaross_xg2.json"
    export.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "_comment": (
            "Kazaross-XG2 match equity table -- the WORK of Neil Kazaross "
            "(XG rollouts to 9 points, GNU Backgammon Supremo full rollouts to "
            "15, extended to 25 by projecting take points). GNU Backgammon is "
            "its distribution vehicle, not its author. This file is the "
            "single canonical export of gammonNet's src/gn_met_table.h -- "
            "read it instead of retranscribing the table. Attribution must "
            "survive any reuse; see gammonNet's THIRD-PARTY.md and "
            "BRIEF.md section 3.3."
        ),
        "source": origin,
        "table": "Kazaross-XG2, œuvre de Neil Kazaross",
        "pre": [{"away_a": i + 1, "away_b": j + 1, "mwc": pre[i][j]}
                for i in range(25) for j in range(25)],
        "post": [{"away": n + 1, "mwc": post[n]} for n in range(len(post))],
    }
    export_text = json.dumps(payload, indent=1, ensure_ascii=False) + "\n"
    export.write_text(export_text)
    print(f"écrit : {export.relative_to(ROOT)}")

    digest = hashlib.sha256(export_text.encode("utf-8")).hexdigest()
    pin = ROOT / "data" / "met_kazaross_xg2.sha256"
    pin.write_text(f"{digest}  met_kazaross_xg2.json\n")
    print(f"écrit : {pin.relative_to(ROOT)} ({digest})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
